spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wikidev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=GMT%2B8
    username: wikidev
    password: wikidev
  redis:
    host: r-uf61jbcdaxobsifyctpd.redis.rds.aliyuncs.com
    port: 6379
    password: Redis000



mybatis:
  mapper-locations: classpath:mapper/**/*.xml



