spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wikidev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=GMT%2B8
    username: wikidev
    password: wikidev
  redis:
    host: 127.0.0.1
    port: 6379



mybatis:
  mapper-locations: classpath:mapper/**/*.xml



